#!/bin/sh
VM_NAME=boot2docker-vm
VBM=VBoxManage

DOCKER_PORT=4243
DOCKER_IP=172.18.42.1
SSH_HOST_PORT=2022

get_latest_release_name() {
    curl 'https://api.github.com/repos/steeve/boot2docker/releases' 2>/dev/null | grep "tag_name" | awk '{print $2}' | sed 's/[",]*//g' | head -1
}

download_latest() {
    LATEST_RELEASE=`get_latest_release_name`
    log "Latest version is $LATEST_RELEASE, downloading..."
    curl -L -o boot2docker.iso "https://github.com/steeve/boot2docker/releases/download/$LATEST_RELEASE/boot2docker.iso"
    log "Done"
}

log() {
    echo "[`date +"%Y-%m-%d %H:%M:%S"`] ${*}"
}

HOST_IP=$(echo $DOCKER_IP | sed 's/\.[0-9]*$/.254/')

init() {

    if `$VBM showvminfo $VM_NAME > /dev/null 2>&1`; then
	    echo "$VM_NAME Virtual Box vm already exists"
	    exit 1
    fi

    VM_MEM=1024
    VM_OSTYPE=Linux26_64
    VM_NIC=virtio
    VM_DISK=./boot2docker.vmdk
    VM_DISK_SIZE=40000
    unamestr=`uname`
    case $unamestr in
        Linux) VM_CPUS=`nproc`;;
        Darwin) VM_CPUS=`sysctl -n hw.physicalcpu`;;
        *) echo "$unamestr not yet supported - please raise an issue" ; exit 1
    esac
    BOOT2DOCKER_ISO=./boot2docker.iso

    log "Creating VM $VM_NAME"
    $VBM createvm --name $VM_NAME --register

    log "Setting VM settings"
    $VBM modifyvm $VM_NAME \
        --ostype $VM_OSTYPE \
        --cpus $VM_CPUS \
        --memory $VM_MEM \
        --rtcuseutc on \
        --acpi on \
        --ioapic on \
        --hpet on \
        --hwvirtex on \
        --vtxvpid on \
        --vtxux on \
        --largepages on \
        --nestedpaging on \
        --firmware bios \
        --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled \
        --boot1 dvd

    log "Setting VM networking"
    $VBM modifyvm $VM_NAME \
        --nic1 hostonly \
        --nictype1 $VM_NIC \
        --cableconnected1 on
    $VBM modifyvm $VM_NAME \
        --nic2 nat \
        --nictype2 $VM_NIC \
        --natdnshostresolver2 on \
        --cableconnected2 on
    if `$VBM showvminfo $VM_NAME | grep Rule | grep ssh > /dev/null`; then
           $VBM modifyvm $VM_NAME \
               --natpf2 delete "ssh"
    fi
    if `$VBM showvminfo $VM_NAME | grep Rule | grep docker > /dev/null`; then
           $VBM modifyvm $VM_NAME \
               --natpf2 delete "docker"
    fi
    $VBM modifyvm $VM_NAME \
        --natpf2 "ssh,tcp,127.0.0.1,$SSH_HOST_PORT,,22" \
        --natpf2 "docker,tcp,127.0.0.1,$DOCKER_PORT,,$DOCKER_PORT"

    if [ ! -e $BOOT2DOCKER_ISO ]; then
        log "boot2docker.iso not found."
        download_latest
    fi

    log "Setting VM disks"
    if `$VBM showvminfo $VM_NAME | grep SATA > /dev/null`; then
        $VBM storagectl $VM_NAME --name "SATA" --remove
    fi

    if [ ! -e $VM_DISK ]; then
        log "Creating $VM_DISK_SIZE Meg hard drive..."
        # closemedium may complain when not needed
        $VBM closemedium disk $VM_DISK > /dev/null 2>&1
        $VBM createhd --format VMDK --filename $VM_DISK --size $VM_DISK_SIZE
    fi

    $VBM storagectl $VM_NAME --name "SATA" --add sata --hostiocache on
    $VBM storageattach $VM_NAME --storagectl "SATA" --port 0 --device 0 --type dvddrive --medium $BOOT2DOCKER_ISO
    $VBM storageattach $VM_NAME --storagectl "SATA" --port 1 --device 0 --type hdd --medium $VM_DISK

    log "Done."
    log "You can now type boot2docker up and wait for the VM to start."
}

do_ssh() {
    ssh -p $SSH_HOST_PORT docker@localhost $1
}

start() {
    if ! is_running; then
        if is_paused; then
            log "Resuming $VM_NAME"
            $VBM controlvm $VM_NAME resume > /dev/null
            wait_vm
            log "Resumed."
        else
            NETWORK_IF=$($VBM list hostonlyifs | grep $HOST_IP -B 4 | grep ^Name: | awk '{print $2}')
            if [ -n "$NETWORK_IF" ]; then
	        log "Using already existing interface: $NETWORK_IF"
            else
	        $VBM hostonlyif create
	        NETWORK_IF=$($VBM list hostonlyifs  | grep ^Name: | tail -n 1 | awk '{print $2}')
	        $VBM hostonlyif ipconfig $NETWORK_IF \
	            --ip $HOST_IP \
	            --netmask 255.255.255.0 >/dev/null
	        log "Created network interface: $NETWORK_IF"
            fi
            $VBM dhcpserver remove \
	        --ifname $NETWORK_IF 2>/dev/null
            DHCP_SERVER_UPPER=$(echo $DOCKER_IP | sed 's/\.[0-9]*$/.252/')
            $VBM dhcpserver add \
	        --ifname $NETWORK_IF \
	        --ip $HOST_IP \
	        --netmask 255.255.255.0 \
	        --lowerip $DOCKER_IP \
	        --upperip $DHCP_SERVER_UPPER \
	        --enable
            $VBM modifyvm $VM_NAME \
                --hostonlyadapter1 $NETWORK_IF

            log "Starting $VM_NAME..."
            $VBM startvm $VM_NAME --type headless > /dev/null &
            wait_vm
            log "Started."
        fi
    else
        log "$VM_NAME is already running."
    fi
}

wait_vm() {
    while ! echo "ping" | nc localhost $SSH_HOST_PORT > /dev/null 2>&1; do
        sleep 1
    done
}

pause() {
    if is_running; then
        log "Pausing $VM_NAME..."
        $VBM controlvm $VM_NAME pause > /dev/null
    else
        log "$VM_NAME is not running."
    fi
}

stop() {
    if is_running; then
        log "Shutting down $VM_NAME..."
        $VBM controlvm $VM_NAME acpipowerbutton > /dev/null
        while is_running; do
            sleep 1
        done
        NETWORK_IF=$($VBM list hostonlyifs | grep $HOST_IP -B 4 | grep ^Name: | awk '{print $2}')
        if [ -n $NETWORK_IF ]; then
          $VBM dhcpserver remove \
              --ifname $NETWORK_IF 2>/dev/null
          $VBM hostonlyif remove $NETWORK_IF
        fi
    else
        log "$VM_NAME is not running."
    fi
}

restart() {
    if is_running; then
        stop && sleep 1 && start
    else
        start
    fi
}

info() {
    $VBM showvminfo $VM_NAME
}

is_running() {
    info | grep "State:\s\+running" > /dev/null
}

is_paused() {
    info | grep "State:\s\+paused" > /dev/null
}

is_stopped() {
    info | grep "State:\s\+powered off" > /dev/null
}

status() {
    if is_running; then
        log "$VM_NAME is running."
        exit 0
    elif is_paused; then
        log "$VM_NAME is suspended."
        exit 1
    else
        log "$VM_NAME is stopped."
        exit 1
    fi
}

delete() {
    if ! is_stopped; then
        log "$VM_NAME needs to be stopped to delete it."
        exit 1
    fi
    $VBM unregistervm --delete $VM_NAME
}

case $1 in
    init | setup) init;;
    start | up) start;;
    pause | suspend) pause;;
    stop | halt | down) stop;;
    restart) restart;;
    status) status;;
    info) info;;
    delete) delete;;
    ssh) shift; do_ssh "$@";;
    download) download_latest;;
    *) echo "Usage $0 {init|start|up|pause|stop|restart|status|info|delete|ssh|download}"; exit 1
esac
